language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*

before_script:
  - composer require --prefer-source --dev symfony/process:${SYMFONY_VERSION}

script: bin/phpunit
